services:
  weaviate:
    image: semitechnologies/weaviate:1.20.0
    container_name: weaviate
    ports:
      - "8090:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 100
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      ENABLE_MODULES: "text2vec-transformers"
      TRANSFORMERS_INFERENCE_API: "http://transformers-inference:8080"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
    depends_on:
      - transformers-inference
    networks:
      - weaviate-network

  transformers-inference:
    image: semitechnologies/transformers-inference:sentence-transformers-paraphrase-multilingual-MiniLM-L12-v2
    container_name: transformers-inference
    networks:
      - weaviate-network

networks:
  weaviate-network:
